version: 0.2

env:
  variables:
    DISABLE_ESLINT_PLUGIN: "true"
    CI: "false"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci --no-progress
  build:
    commands:
      - npm run build
      - mv build dist

artifacts:
  files:
    - "dist/**/*"
  name: FrontendBuildOutput

cache:
  paths:
    - "~/.npm/**/*"
